version: '3.8'
services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: fitmeup-landing
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
